### ISSUE TITLE
Inspect merge issue

### ISSUE THREAD

**Issue by Foopyo** [ori-rando/wotw-seedgen#12]
On the commit 29ea4d3f1e775290628e051209b0b61d87f8cd38 there was some merge issue which introduced logic bugs. This commit need to be inspected a bit more to see if nothing got reverted.

**Comment by Foopyo** [comment]
I still need to verify if the wellspring paths are the one I did write (validation work hasn't been done yet but still)

**Comment by SiriusAshling** [comment]
Pull request #3 looks like it needs some review in general

**Comment by SiriusAshling** [comment]
The source of issues seems to be this merge which didn't resolve conflicts correctly: 92e2b81e26881e70da0f21146dae949d24d80f46

Suggestion for the future: Use less branches? All the per-region branches mostly seem to add clutter and room for errors.

**Comment by SiriusAshling** [comment]
Reviewing the merge above now, list of commits from the inner-wellspring branch:
29ea4d3f1e775290628e051209b0b61d87f8cd38
4a7b3c6ed4130f7d14c02dcbd782c78ed805d022
aa4161c8150e3df549cd686acde712776fdee569
28398eac225544a8306ce538189a36ca96794e94
da09960bc3f754c822b72451b708589dbfefbe0f
63053eae80eca9c5c6804935c40f873b99b04335

**Comment by SiriusAshling** [comment]
The commits dc61362a49813b1d2d28efb6803b20cd7a797b54 and b5c1c7840b42064ef3725de471fca86a43f8fb59 were overwritten in 29ea4d3f1e775290628e051209b0b61d87f8cd38, all the changes from inner-wellspring are still present.

c66bc8ba226743a510dbd6c82944e32ebaa79747 reconstructs the changes of the overwritten commits with the exception of adding NonGladesTeleporter at the Midnight Burrows teleporter, which the original commit did not have. So I guess that's another bug fixed along the way :p
