### ISSUE TITLE
Spoiler separated from seed file

### ISSUE THREAD

**Issue by Foopyo** [ori-rando/wotw-seedgen#15]
Having a way to view spoilers without needing to open the seed in a text editor. Can be a separated text file or a way to open spoilers in the launcher directly.
Multiworld spoilers should be on a single file rather than having one per seed.
This will probably require to change how the Disable Spoilers option works, if it's still needed at all.

**Comment by timoschwarzer** [comment]
(If there are no good arguments for using plain text files, I'd suggest some JSON format so I can display spoilers with some neat UI)

**Comment by SiriusAshling** [comment]
Having the spoiler human-readable/human-pleasant would be convenient.
E.g. when embedding a spoiler into discord opening the discord text preview is much more convenient than downloading the file and starting the launcher.
Of course this doesn't have to be mutually exclusive with storing the data in a predictable format that would be easy to deconstruct

**Comment by SiriusAshling** [comment]
Example spoilers form blind forest for reference:
default spoiler https://orirando.com/generator/spoiler/5158364879257600
"item list" https://orirando.com/generator/aux_spoiler/5158364879257600?exclude=EX+KS+AC+EC+HC+MS

I personally always found the default spoiler difficult to read, it might be worth exploring more semantic formats.
The item list seems neat and useful and intuitive, would like to have that in there

**Comment by SiriusAshling** [comment]
Synopsis of a conversation with Muffin about what are useful aspects of the Blind Forest (default) spoiler format:
- List of unlocked pickup locations (see where "big" and "small" progressions were, pattern learning on what skills unlock)
- Explicit mention if something was forced progression (insight into generation process)
- Coordinates on pickup locations (if you don't know the name)
- numbered steps (easier communication when talking about a spoiler)
- ordering of items in the same step (skils -> TPs -> MS -> KS -> Cells)

**Comment by timoschwarzer** [comment]
@SiriusAshling what about a standard JSON format that contains all information to derive all wanted human readable formats from it?

I want to prevent another parser for yet another new format. This way, the launcher could have one (or more for more formats) "Copy spoiler text" button.

What that text is should be controlled by seedgen, so we don't have changes in seedgen that break/depend on changes in ui. So seedgen would need to

1. save spoilers in some JSON format
2. a wasm interface to convert that JSON into all of the text formats wanted.

The JSON will be used by the launcher to display a spoiler map and possibly a progression heatmap.

**Comment by SiriusAshling** [comment]
Json serialization in the launcher wasm would make sense to me.

The seedgen library itself is to be used by other rust code which can read the spoiler data out of the rust structure itself, so I don't think the library needs that serialization.

The launcher wasm could still fetch the Rust structure for spoilers and serialize it without the library having that functionality, that way the part of the code which is only relevant to the launcher doesn't have to be compiled for everything else.

Of course this will only work once the launcher actually uses wasm for seed generation (which would allow to remove a lot of bloat from the library in other similar situations as well)

**Comment by SiriusAshling** [comment]
Seems like serde even has direct support for serialization of structs from other crates, which would likely trivialize this approach https://serde.rs/remote-derive.html

**Comment by timoschwarzer** [comment]
> Of course this will only work once the launcher actually uses wasm for seed generation (which would allow to remove a lot of bloat from the library in other similar situations as well)

Hence why seedgen should be able to generate text spoilers from the JSON. Then it also works with seeds generates on the server.

**Comment by SiriusAshling** [comment]
I'm not sure I understand this aspect?
I would assume the website can use the same procedure as the local launcher, why would it do something else?

**Comment by timoschwarzer** [comment]
Because then I don't need to store the spoilers in all available formats but only in JSON

**Comment by SiriusAshling** [comment]
This is the first time items are being ordered/sorted, so some design on ordering is needed.

Initial design:
- Ordering is "low" to "high"
- Any "removing" item kind is ordered directly after the corresponding "granting" kind
- Relic < Water < Skill < Teleporter < Resource < Shard < Bonus Item < Bonus Upgrade < Spirit Light < Message < UberState Command < System Command < Wheel Command < Shop Command < System Message
- Deeper ordering (skill ordering, teleporter ordering etc.) is generally based on the IDs used in seed language
- Further details are left to chance of implementation without specific definition

**Comment by timoschwarzer** [comment]
My goal is to have one single machine readable (JSON) source of truth spoiler format that contains all needed information to generate other human readable text formats from it.

> I at least didn't intend to create multiple formats of the logic spoiler, Ori 1 only offered one as well.

I'd find it interesting to display progression heat maps for seeds in the launcher, or at least some graphical representation of the spoiler like a progression path. All of that would need a machine readable format.

This format is not useful to paste and send in Discord though, as you mentioned. So we need a short, human readable text format as well.

**Comment by SiriusAshling** [comment]
Additional discussion in https://discord.com/channels/942484331572658196/983643252966166578/983643257739292712

**Comment by SiriusAshling** [comment]
Summary of the implementation:

Spoiler struct: https://github.com/ori-rando/wotw-seedgen/blob/breaking-changes/wotw_seedgen/src/generator/spoiler.rs
Alongside the meta information about how and where it was placed, this contains clones of all the placed items.
Cloning every placed items didn't seem to cause a major performance regression, and this gives more flexibility since it allows requesting any information that an Item can give.
To avoid the huge overhead default json serialization of items would cause, they are serialized into and from the seed language representation.
This may cause some issues currently because I didn't implement the discrepancies between seed and header language for parsing (e.g. quoted vs. unquoted strings).

The CLI now creates a spoiler.txt by default, passing a `--json-spoiler` flag has it create a spoiler.json instead.

No work on item lists yet

**Comment by SiriusAshling** [comment]
Example run
[spoiler.zip](https://github.com/ori-rando/wotw-seedgen/files/8884707/spoiler.zip)
