### ISSUE TITLE
No Combat logic

### ISSUE THREAD

**Issue by SiriusAshling** [ori-rando/wotw-seedgen#31]
No Combat changes a number of world states which are only partially logically supported.
This leads to intuition issues where e.g. the Glades Combat Shrine shows out of logic while the harder to reach pickup above it shows in logic.

It would be more intuitive if the used states were logically implemented as we usually do for headers.

**Comment by SiriusAshling** [comment]
Current status of no combat states:

- [ ] Combat Shrines: unsupported
- [ ] Marsh Cave Fight Arena: unsupported
- [x] Baur's Reach Fight Arena: supported
- [ ] Marsh Burrow Arena: supported in kii
- [ ] Double Jump Tree Fight Arena: unsupported
- [x] Weeping Ridge Elevator Fight: supported
- [ ] Wellspring Second Floor Spin Arena: state mismatch (sets 37858|8487=5, logical state is 37858|8487=2, maybe change the logical state to include opening the door?)
- [x] Pools Waterdash Arena: supported
- [x] Howl Fight: supported
- [x] Hornbug Fight: supported
- [x] Willow Rock Boss Fight: supported (but irrelevant regardless)
- [ ] Kwolok Fight: unsupported
- [ ] Mora Fight: unsupported

Since implicit assumptions can sneak in sometimes, it is recommended to check for the supported states as well that all the relevant paths exist for when the state is already set form spawn.
**Important** for the Kwolok and Mora Fight, only the combat part is skipped, the movement part still has to be completed. To represent this, one state per boss for all the combat parts combined should work, then using that state and the necessary movement abilities for the escapes in the actual boss paths.

**Comment by SiriusAshling** [comment]
Addition: The Pools Waterdash Arena is incorrectly implemented.
For the needs of no combat it will be required to add a state for the purple barrier in front of the arena, since the no combat header removes the arena combat but not the purple barrier

**Comment by SiriusAshling** [comment]
Pools Waterdash Arena is now fixed through ca51ea0262553b2480c6bc4e7d81956d9b97da44

**Comment by Foopyo** [comment]
Changes are on the [combat-states](https://github.com/ori-rando/wotw-seedgen/tree/combat-states) branch. Not closing the ticket since new paths still need to get validated by someone else.
