### ISSUE TITLE
Add Reach Escape CS to skippable cutscenes

### ISSUE THREAD

**Issue by toadettexmushina** [ori-rando/wotw-seedgen#43]
Add the cutscene at the start of reach escape to the skippable cutscenes header. Maybe also the part of the cutscene after the escape that you can't skip.

Yes, I know it *can* be skipped manually, but doing so is difficult, and only saves a little time.
That makes it different from the Wellspring escape cutscene, where skipping it lets you access the revisit pickup early.
(Also Ore-pa-piii forever <3)
But I guess skipping that cutscene would be ok too.

I'm personally ok with this resulting in a death, like the Kwolok escape, since that's much quicker than watching the whole cutscene.

You could also have the main Willow's End door already open instead of having to watch the stones explode, since that doesn't actually have any requirements, just takes a couple seconds, but that's a pretty minor one.

And there's also the spooked ori cutscene at the feeding grounds

**Comment by Foopyo** [comment]
Done in 2.0
