### ISSUE TITLE
Syntax for Ability Swaps

### ISSUE THREAD

**Issue by FloSH02** [ori-rando/wotw-seedgen#5]
current possible syntax:
  for LaunchSwaps:
    Launch, Sentry=0 OR Flash=0 OR Blaze=0 OR Flap OR Regenerate OR Grenade=0 OR Shuriken=0 OR Hammer OR Spear=0 OR Bow=0 OR Sword
  for SentrySwaps:
    Sentry=1, Flash=0 OR Blaze=0 OR Flap OR Regenerate OR Grenade=0 OR Shuriken=0 OR Hammer OR Spear=0 OR Bow=0 OR Sword OR Launch
wished syntax:
  Launch, AbilitySwap
  Sentry=1, AbilitySwap

**Comment by SiriusAshling** [comment]
implemented in 96b0d6d1f5e30c2bc2d94fa6ab767f3ebb84ce9c
