### ISSUE TITLE
Item Weights via Headers

### ISSUE THREAD

**Issue by Coder23848** [ori-rando/wotw-seedgen#69]
The ability to set the weight of items in the pool via headers. This would be a good way to balance a seed (make Launch rarer instead of preplacing or fragmenting it), and it would allow changing the progression without completely removing items.
`!!weight <float> <item>` syntax, maybe?

**Comment by SiriusAshling** [comment]
On a technical level the implementation should be simple.

I'm concerned it might have negative implications for the randomizer design?
Item weights are a complicated topic with many factors and implications, for instance the weight of placing a progression is not only based on the base item weights, but also on the newly reachable locations the progression would unlock.

From the seed generator perspective, we try to balance item progressions to be varied, which often involves more than adjusting the base item weights.
As such the practical implications of a header using the potential `!!weight` command would change unpredictably when we do balance changes on our side not related to base weights.

In the current state I think there is still a good amount of polish possible to the algorithm of choosing progressions, and it might be preferrable to reach a more stable state of that algorithm before exposing detail configurations that may have surprising results?

**Comment by Coder23848** [comment]
Good point.
Closing this, it can always be reopened if a stable solution appears.
