### ISSUE TITLE
Has anyone seen this before?

### ISSUE THREAD

**Issue by Coder23848** [ori-rando/wotw-seedgen#72]
I was trying to do a path with Bash, and then the skeeto I was using started spinning in place. After I died, it froze. Is this a known glitch? It looks like it would be useful for something, if it can be replicated.

**Properties:**
If killed or despawned, it will respawn in the same state.
It takes damage, but does not flinch. Bashing off of it only moves Ori.
If killed, it falls straight down and disappears after a few seconds. It doesn't change its pose, and it doesn't dissolve.
The debug AI display lists it as "reacting", even when it's newly spawned.
Upon leaving an coming back, it returns to normal.

I have no idea how this happened, but I suspect it's related to the crusher freeze glitch.

https://user-images.githubusercontent.com/103940315/167271261-c94c044f-48ec-4458-8687-736cde145eca.mp4

**Comment by Coder23848** [comment]
Update: I've managed to replicate it a few times, and it seems to be doable by dying, having a skeeto die immediately afterward, and mashing Bash the whole time; the skeeto plays the death animation upon Ori respawning, which prevents it from doing anything else.
My guess is that something allows you to bash its corpse for a frame while respawning.

Unfortunately, this doesn't seem to be useful for anything, since there's no way to move the skeeto once it's frozen.

**Comment by timoschwarzer** [comment]
Yes, this happens when you die while the skeeto is spinning and you have a checkpoint outside the loaded area.

**Comment by Coder23848** [comment]
Neat.
Closing this, as I'm confident it's not logic relevant.

**Comment by Coder23848** [comment]
wait it's already closed lol

**Comment by Foopyo** [comment]
Hey @Coder23848 , we have a Discord server specifically for the randomizer development (used for both Will of the Wisps and Blind Forest). If you are interested in joining it, it would make it easier for us to share this kind of information 👍[https://discord.gg/sfUr8ra5P7](https://discord.gg/sfUr8ra5P7)
